# Base settings
name:             toubsen.de
timezone:         Europe/Berlin

# gh-pages config
markdown:         kramdown
kramdown:
  input:          GFM
  hard_wrap:      false
highlighter:      rouge
sass:
  sass_dir:       _sass
  style:          compressed

# Dependencies
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

# Permalinks
permalink:         /blog/:year/:month/:day/:title.html
paginate_path:    'blog/:num'

# Setup
title:            TV
tagline:          'toubsen.de'
description:      'gnothi seauton'
url:              http://www.toubsen.de

author:
  name:           'Tobias Varol'
  url:            https://twitter.com/tobiasvarol

paginate:         5
